import type { Metadata } from "next";

import { Space_Grotesk } from "next/font/google";
import "../globals.css";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Topbar from "@/components/shared/Topbar";
import RightSidebar from "@/components/shared/RightSidebar";


const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // select what you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased `}
        
      >
        <main className="flex flex-row ">
        <LeftSidebar />
          <section className="flex min-h-screen flex-1 flex-col">
            <Topbar />
            {children}
          </section>
        <RightSidebar />
        </main>
      </body>
    </html>
  );
}
